/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.6/samples
 */
plugins {
    java
}

group = "com.ez_mode"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
}

dependencies {
    // log4j2 for logging
    implementation("org.apache.logging.log4j:log4j-api:2.20.0")
    implementation("org.apache.logging.log4j:log4j-core:2.20.0")

    // swing laf
    implementation("com.formdev:flatlaf:3.0")

    // JUnit for testing
    testImplementation("junit:junit:4.13.2")
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}