name: Format

on:
  push:
    tags-ignore: 'reformat'

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # v2 minimum required
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace"
          skip-commit: true
      - name: Commit changes
        run: git tag reformat && git commit -a -m "Reformat code" && git push origin reformat
